version: "3.7"
volumes:
  data:
    external: true
networks:
  web:
    external: true
services:
  web:
    image: nginx:1.22.0-alpine
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.${site_name}_web.rule=Host(`${domain}`)"
    - "traefik.http.routers.${site_name}_web.entrypoints=web"
    - "traefik.http.routers.${site_name}_websecure.rule=Host(`${domain}`)"
    - "traefik.http.routers.${site_name}_websecure.entrypoints=websecure"
    - "traefik.http.routers.${site_name}_websecure.tls.certresolver=myresolver"
    - "traefik.docker.network=web"
    hostname: ${domain}
    container_name: ${site_name}_web
    networks:
      - web
    volumes:
      - data:/var/www/
      - ./Build/nginx/confs/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
  php:
    build:
      context: "./Build/php/"
    environment:
      - localdir=/var/www/public
    networks:
      - web
    container_name: ${site_name}_php
    volumes:
      - data:/var/www
    restart: always